version: '3.8'

services:
  db:
    image: postgres:16.4
    container_name: rss_server
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: donkey6
      POSTGRES_DB: rss_server
    ports:
      - "5432:5432"
